export const defaultImages = [
  {
    id: "TJhnoLhuCZs",
    slug: "rock-mountain-covered-by-snow-TJhnoLhuCZs",
    alternative_slugs: {
      en: "rock-mountain-covered-by-snow-TJhnoLhuCZs",
      es: "montana-rocosa-cubierta-de-nieve-TJhnoLhuCZs",
      ja: "雪に覆われた岩山-TJhnoLhuCZs",
      fr: "montagne-rocheuse-recouverte-de-neige-TJhnoLhuCZs",
      it: "montagna-rocciosa-coperta-di-neve-TJhnoLhuCZs",
      ko: "눈으로-덮인-바위-산-TJhnoLhuCZs",
      de: "felsberg-mit-schnee-bedeckt-TJhnoLhuCZs",
      pt: "montanha-rochosa-coberta-de-neve-TJhnoLhuCZs",
      id: "gunung-batu-tertutup-salju-TJhnoLhuCZs",
    },
    created_at: "2018-11-03T14:26:42Z",
    updated_at: "2026-03-01T00:10:43Z",
    promoted_at: "2018-11-03T14:54:59Z",
    width: 3159,
    height: 4824,
    color: "#f3f3f3",
    blur_hash: "LZM7r.S5xuW=.At7MxxaR.%L?aRj",
    description: "Something special shot in 2014.",
    alt_description: "rock mountain covered by snow",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1541255048924-c237ff6875ac?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1541255048924-c237ff6875ac?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1541255048924-c237ff6875ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1541255048924-c237ff6875ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1541255048924-c237ff6875ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1541255048924-c237ff6875ac",
    },
    links: {
      self: "https://api.unsplash.com/photos/rock-mountain-covered-by-snow-TJhnoLhuCZs",
      html: "https://unsplash.com/photos/rock-mountain-covered-by-snow-TJhnoLhuCZs",
      download:
        "https://unsplash.com/photos/TJhnoLhuCZs/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/TJhnoLhuCZs/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 329,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-04-06T14:20:12Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "oHdIYDPpoRM",
      updated_at: "2026-02-23T13:00:11Z",
      username: "martinjernberg",
      name: "Martin Jernberg",
      first_name: "Martin",
      last_name: "Jernberg",
      twitter_username: null,
      portfolio_url: "http://www.martinjernberg.com/",
      bio: null,
      location: "Denver, CO",
      links: {
        self: "https://api.unsplash.com/users/martinjernberg",
        html: "https://unsplash.com/@martinjernberg",
        photos: "https://api.unsplash.com/users/martinjernberg/photos",
        likes: "https://api.unsplash.com/users/martinjernberg/likes",
        portfolio: "https://api.unsplash.com/users/martinjernberg/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1716438065741-9f2b799b9aedimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1716438065741-9f2b799b9aedimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1716438065741-9f2b799b9aedimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "martin.jernberg",
      total_collections: 0,
      total_likes: 30,
      total_photos: 43,
      total_free_photos: 43,
      total_promoted_photos: 34,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "martin.jernberg",
        portfolio_url: "http://www.martinjernberg.com/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 6D",
      name: "Canon, EOS 6D",
      exposure_time: "1/1000",
      aperture: "6.3",
      focal_length: "35.0",
      iso: 160,
    },
    location: {
      name: "Aiguille du Midi, Chamonix, France",
      city: "Chamonix",
      country: "France",
      position: {
        latitude: 45.8793111,
        longitude: 6.88742430000002,
      },
    },
    views: 4324641,
    downloads: 10211,
  },
  {
    id: "o5oaFkNfNOI",
    slug: "photo-of-island-during-daytime-o5oaFkNfNOI",
    alternative_slugs: {
      en: "photo-of-island-during-daytime-o5oaFkNfNOI",
      es: "foto-de-la-isla-durante-el-dia-o5oaFkNfNOI",
      ja: "昼間の島の写真-o5oaFkNfNOI",
      fr: "photo-de-lile-pendant-la-journee-o5oaFkNfNOI",
      it: "foto-dellisola-durante-il-giorno-o5oaFkNfNOI",
      ko: "낮-동안의-섬-사진-o5oaFkNfNOI",
      de: "foto-der-insel-tagsuber-o5oaFkNfNOI",
      pt: "foto-da-ilha-durante-o-dia-o5oaFkNfNOI",
      id: "foto-pulau-di-siang-hari-o5oaFkNfNOI",
    },
    created_at: "2018-02-04T22:27:09Z",
    updated_at: "2026-03-01T00:17:09Z",
    promoted_at: "2018-02-05T09:36:46Z",
    width: 5933,
    height: 3961,
    color: "#d9c0c0",
    blur_hash: "LQI;ek9b4.oe~XWBRjbH-=WBRkbH",
    description:
      "Another day before newyear in wonderful dalsland. The cold air came and brought us some winter chills. It was totally calm and no noise was heard. We also produced a timelapse which is not edited yet.",
    alt_description: "photo of island during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1517782902678-70c53f6dd2b9?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1517782902678-70c53f6dd2b9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1517782902678-70c53f6dd2b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1517782902678-70c53f6dd2b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1517782902678-70c53f6dd2b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1517782902678-70c53f6dd2b9",
    },
    links: {
      self: "https://api.unsplash.com/photos/photo-of-island-during-daytime-o5oaFkNfNOI",
      html: "https://unsplash.com/photos/photo-of-island-during-daytime-o5oaFkNfNOI",
      download:
        "https://unsplash.com/photos/o5oaFkNfNOI/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/o5oaFkNfNOI/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 456,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "tMjNnW9Br5M",
      updated_at: "2026-02-24T09:44:18Z",
      username: "gaspard_photo_",
      name: "Jasper Graetsch",
      first_name: "Jasper",
      last_name: "Graetsch",
      twitter_username: null,
      portfolio_url: "https://www.instagram.com/gaspard.photo_/",
      bio: null,
      location: "Kiel, Germany",
      links: {
        self: "https://api.unsplash.com/users/gaspard_photo_",
        html: "https://unsplash.com/@gaspard_photo_",
        photos: "https://api.unsplash.com/users/gaspard_photo_/photos",
        likes: "https://api.unsplash.com/users/gaspard_photo_/likes",
        portfolio: "https://api.unsplash.com/users/gaspard_photo_/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1517844522560-62b094deae21?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1517844522560-62b094deae21?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1517844522560-62b094deae21?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "gaspard.photo_",
      total_collections: 0,
      total_likes: 93,
      total_photos: 21,
      total_free_photos: 21,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: true,
      social: {
        instagram_username: "gaspard.photo_",
        portfolio_url: "https://www.instagram.com/gaspard.photo_/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D600",
      name: "NIKON CORPORATION, NIKON D600",
      exposure_time: "1/800",
      aperture: "2.8",
      focal_length: "70.0",
      iso: 500,
    },
    location: {
      name: "Halevattnet, Färgelanda, Sweden",
      city: "Färgelanda",
      country: "Sweden",
      position: {
        latitude: 58.5830556,
        longitude: 12.1166667,
      },
    },
    views: 9261659,
    downloads: 15303,
  },
  {
    id: "-tm0PIhVHFQ",
    slug: "a-forest-filled-with-lots-of-tall-trees--tm0PIhVHFQ",
    alternative_slugs: {
      en: "a-forest-filled-with-lots-of-tall-trees--tm0PIhVHFQ",
      es: "un-bosque-lleno-de-muchos-arboles-altos--tm0PIhVHFQ",
      ja: "背の高い木々がたくさん生い茂る森--tm0PIhVHFQ",
      fr: "une-foret-remplie-de-grands-arbres--tm0PIhVHFQ",
      it: "una-foresta-piena-di-molti-alberi-ad-alto-fusto--tm0PIhVHFQ",
      ko: "키-큰-나무가-많이-우거진-숲--tm0PIhVHFQ",
      de: "ein-wald-mit-vielen-hohen-baumen--tm0PIhVHFQ",
      pt: "uma-floresta-cheia-de-arvores-altas--tm0PIhVHFQ",
      id: "hutan-yang-dipenuhi-dengan-banyak-pohon-tinggi--tm0PIhVHFQ",
    },
    created_at: "2023-09-26T09:02:37Z",
    updated_at: "2026-03-01T04:55:47Z",
    promoted_at: "2024-02-15T14:33:15Z",
    width: 5116,
    height: 3411,
    color: "#262626",
    blur_hash: "LtHBVaslRjoet7NGbIfk0LWXxtay",
    description: null,
    alt_description: "a forest filled with lots of tall trees",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1695718948137-1f4d1d5ba889?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1695718948137-1f4d1d5ba889?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1695718948137-1f4d1d5ba889?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1695718948137-1f4d1d5ba889?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1695718948137-1f4d1d5ba889?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1695718948137-1f4d1d5ba889",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-forest-filled-with-lots-of-tall-trees--tm0PIhVHFQ",
      html: "https://unsplash.com/photos/a-forest-filled-with-lots-of-tall-trees--tm0PIhVHFQ",
      download:
        "https://unsplash.com/photos/-tm0PIhVHFQ/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/-tm0PIhVHFQ/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 195,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "rejected",
      },
      nature: {
        status: "approved",
        approved_on: "2023-09-28T19:32:30Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "gGceyZNHUAM",
      updated_at: "2026-02-26T11:03:02Z",
      username: "visualsbying",
      name: "Ingmar",
      first_name: "Ingmar",
      last_name: null,
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/visualsbying",
        html: "https://unsplash.com/@visualsbying",
        photos: "https://api.unsplash.com/users/visualsbying/photos",
        likes: "https://api.unsplash.com/users/visualsbying/likes",
        portfolio: "https://api.unsplash.com/users/visualsbying/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1768155461662-1387c7795066image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1768155461662-1387c7795066image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1768155461662-1387c7795066image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "Visualsbyingmar",
      total_collections: 4,
      total_likes: 367,
      total_photos: 547,
      total_free_photos: 547,
      total_promoted_photos: 103,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "Visualsbyingmar",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "X-T30 II",
      name: "FUJIFILM, X-T30 II",
      exposure_time: "1/100",
      aperture: "5.0",
      focal_length: "23.0",
      iso: 800,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: 0,
        longitude: 0,
      },
    },
    views: 11479179,
    downloads: 99353,
  },
  {
    id: "mtPBBZyoWLE",
    slug: "green-trees-near-brown-mountain-under-cloudy-sky-during-daytime-mtPBBZyoWLE",
    alternative_slugs: {
      en: "green-trees-near-brown-mountain-under-cloudy-sky-during-daytime-mtPBBZyoWLE",
      es: "arboles-verdes-cerca-de-brown-mountain-bajo-el-cielo-nublado-durante-el-dia-mtPBBZyoWLE",
      ja: "日中の曇り空の下茶色の山の近くの緑の木々-mtPBBZyoWLE",
      fr: "arbres-verts-pres-de-la-montagne-brune-sous-un-ciel-nuageux-pendant-la-journee-mtPBBZyoWLE",
      it: "alberi-verdi-vicino-alla-montagna-marrone-sotto-il-cielo-nuvoloso-durante-il-giorno-mtPBBZyoWLE",
      ko: "낮-동안-흐린-하늘-아래-갈색-산-근처의-푸른-나무-mtPBBZyoWLE",
      de: "grune-baume-in-der-nahe-von-brown-mountain-unter-bewolktem-himmel-tagsuber-mtPBBZyoWLE",
      pt: "arvores-verdes-perto-da-montanha-marrom-sob-o-ceu-nublado-durante-o-dia-mtPBBZyoWLE",
      id: "pohon-hijau-di-dekat-gunung-coklat-di-bawah-langit-mendung-pada-siang-hari-mtPBBZyoWLE",
    },
    created_at: "2020-01-27T19:08:43Z",
    updated_at: "2026-03-01T00:11:56Z",
    promoted_at: "2020-01-28T05:18:02Z",
    width: 6720,
    height: 4480,
    color: "#262626",
    blur_hash: "LgF=v}IVE1Rj~WM|R*WBNGkCxtf5",
    description: null,
    alt_description:
      "green trees near brown mountain under cloudy sky during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1580151899419-ba2b99eac662?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1580151899419-ba2b99eac662?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1580151899419-ba2b99eac662?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1580151899419-ba2b99eac662?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1580151899419-ba2b99eac662?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1580151899419-ba2b99eac662",
    },
    links: {
      self: "https://api.unsplash.com/photos/green-trees-near-brown-mountain-under-cloudy-sky-during-daytime-mtPBBZyoWLE",
      html: "https://unsplash.com/photos/green-trees-near-brown-mountain-under-cloudy-sky-during-daytime-mtPBBZyoWLE",
      download:
        "https://unsplash.com/photos/mtPBBZyoWLE/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/mtPBBZyoWLE/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 183,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-04-06T14:20:12Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "EwqQvCNZz7M",
      updated_at: "2026-02-23T20:38:55Z",
      username: "jmvillejo",
      name: "Jed Villejo",
      first_name: "Jed",
      last_name: "Villejo",
      twitter_username: null,
      portfolio_url: "https://jedvillejo.squarespace.com/",
      bio: "Photographer and Videographer based out of North County San Diego!",
      location: "Oceanside, CA",
      links: {
        self: "https://api.unsplash.com/users/jmvillejo",
        html: "https://unsplash.com/@jmvillejo",
        photos: "https://api.unsplash.com/users/jmvillejo/photos",
        likes: "https://api.unsplash.com/users/jmvillejo/likes",
        portfolio: "https://api.unsplash.com/users/jmvillejo/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1504820016671-17d3b05b92ac?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1504820016671-17d3b05b92ac?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1504820016671-17d3b05b92ac?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "jedvillejo",
      total_collections: 0,
      total_likes: 22,
      total_photos: 189,
      total_free_photos: 189,
      total_promoted_photos: 82,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "jedvillejo",
        portfolio_url: "https://jedvillejo.squarespace.com/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS R",
      name: "Canon, EOS R",
      exposure_time: "1/250",
      aperture: "5.0",
      focal_length: "35.0",
      iso: 500,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 15919394,
    downloads: 12305,
  },
  {
    id: "4M-5WBrG5-c",
    slug: "blue-body-of-water-4M-5WBrG5-c",
    alternative_slugs: {
      en: "blue-body-of-water-4M-5WBrG5-c",
      es: "cuerpo-de-agua-azul-4M-5WBrG5-c",
      ja: "青い水域-4M-5WBrG5-c",
      fr: "plan-deau-bleu-4M-5WBrG5-c",
      it: "specchio-dacqua-blu-4M-5WBrG5-c",
      ko: "푸른-수역-4M-5WBrG5-c",
      de: "blaues-gewasser-4M-5WBrG5-c",
      pt: "corpo-de-agua-azul-4M-5WBrG5-c",
      id: "badan-air-biru-4M-5WBrG5-c",
    },
    created_at: "2014-06-27T22:40:34Z",
    updated_at: "2026-03-01T03:46:07Z",
    promoted_at: "2014-06-27T22:40:34Z",
    width: 8134,
    height: 5562,
    color: "#a6c0c0",
    blur_hash: "LgEf{5?us:WB_N%Lt7fkIVMybHkB",
    description: "Mountains on the opposite shore",
    alt_description: "blue body of water",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/39/wdXqHcTwSTmLuKOGz92L_Landscape.jpg?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/39/wdXqHcTwSTmLuKOGz92L_Landscape.jpg?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/39/wdXqHcTwSTmLuKOGz92L_Landscape.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/39/wdXqHcTwSTmLuKOGz92L_Landscape.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/39/wdXqHcTwSTmLuKOGz92L_Landscape.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/39/wdXqHcTwSTmLuKOGz92L_Landscape.jpg",
    },
    links: {
      self: "https://api.unsplash.com/photos/blue-body-of-water-4M-5WBrG5-c",
      html: "https://unsplash.com/photos/blue-body-of-water-4M-5WBrG5-c",
      download:
        "https://unsplash.com/photos/4M-5WBrG5-c/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/4M-5WBrG5-c/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 1323,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "BLKyGeASsZ4",
      updated_at: "2026-02-23T10:13:40Z",
      username: "nickwest",
      name: "Nick West",
      first_name: "Nick",
      last_name: "West",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/nickwest",
        html: "https://unsplash.com/@nickwest",
        photos: "https://api.unsplash.com/users/nickwest/photos",
        likes: "https://api.unsplash.com/users/nickwest/likes",
        portfolio: "https://api.unsplash.com/users/nickwest/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1462109452442-220ea92849f4?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1462109452442-220ea92849f4?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1462109452442-220ea92849f4?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 3,
      total_free_photos: 3,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark III",
      name: "Canon, EOS 5D Mark III",
      exposure_time: "1/125",
      aperture: "13.0",
      focal_length: "45.0",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 40243116,
    downloads: 109210,
  },
  {
    id: "GZd3l4Yxdxs",
    slug: "mountain-with-trees-covered-with-fogs-GZd3l4Yxdxs",
    alternative_slugs: {
      en: "mountain-with-trees-covered-with-fogs-GZd3l4Yxdxs",
      es: "montana-con-arboles-cubiertos-de-niebla-GZd3l4Yxdxs",
      ja: "霧に覆われた木々の山-GZd3l4Yxdxs",
      fr: "montagne-avec-des-arbres-couverts-de-brouillards-GZd3l4Yxdxs",
      it: "montagna-con-alberi-coperti-di-nebbie-GZd3l4Yxdxs",
      ko: "안개로-뒤덮인-나무가-있는-산-GZd3l4Yxdxs",
      de: "berg-mit-baumen-die-in-nebel-gehullt-sind-GZd3l4Yxdxs",
      pt: "montanha-com-arvores-cobertas-de-nevoeiros-GZd3l4Yxdxs",
      id: "gunung-dengan-pepohonan-yang-tertutup-kabut-GZd3l4Yxdxs",
    },
    created_at: "2018-12-15T20:39:20Z",
    updated_at: "2026-03-01T00:21:54Z",
    promoted_at: "2018-12-17T12:44:10Z",
    width: 4930,
    height: 2775,
    color: "#8ca6f3",
    blur_hash: "LjDwIat1RkWE_Nt6WFWXxlt5WEa#",
    description: null,
    alt_description: "mountain with trees covered with fogs",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1544906331-ebabd2fe0997?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1544906331-ebabd2fe0997?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1544906331-ebabd2fe0997?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1544906331-ebabd2fe0997?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1544906331-ebabd2fe0997?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1544906331-ebabd2fe0997",
    },
    links: {
      self: "https://api.unsplash.com/photos/mountain-with-trees-covered-with-fogs-GZd3l4Yxdxs",
      html: "https://unsplash.com/photos/mountain-with-trees-covered-with-fogs-GZd3l4Yxdxs",
      download:
        "https://unsplash.com/photos/GZd3l4Yxdxs/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/GZd3l4Yxdxs/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 443,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2020-04-06T14:20:09Z",
      },
      nature: {
        status: "approved",
        approved_on: "2020-04-06T14:20:12Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "HW4bvDAlVk4",
      updated_at: "2026-02-25T11:37:32Z",
      username: "leonoverweel",
      name: "Leon Overweel",
      first_name: "Leon",
      last_name: "Overweel",
      twitter_username: "layon_overwhale",
      portfolio_url: "https://leonoverweel.com",
      bio: null,
      location: "Amsterdam",
      links: {
        self: "https://api.unsplash.com/users/leonoverweel",
        html: "https://unsplash.com/@leonoverweel",
        photos: "https://api.unsplash.com/users/leonoverweel/photos",
        likes: "https://api.unsplash.com/users/leonoverweel/likes",
        portfolio: "https://api.unsplash.com/users/leonoverweel/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1610833617141-3d0e24a986dbimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1610833617141-3d0e24a986dbimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1610833617141-3d0e24a986dbimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "leonoverweel",
      total_collections: 0,
      total_likes: 1,
      total_photos: 28,
      total_free_photos: 28,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "leonoverweel",
        portfolio_url: "https://leonoverweel.com",
        twitter_username: "layon_overwhale",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 60D",
      name: "Canon, EOS 60D",
      exposure_time: "1/400",
      aperture: "5.6",
      focal_length: "106.0",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 17655558,
    downloads: 50475,
  },
  {
    id: "mOBNSq7eCvk",
    slug: "an-abstract-photo-of-a-blue-building-with-a-blue-sky-in-the-background-mOBNSq7eCvk",
    alternative_slugs: {
      en: "an-abstract-photo-of-a-blue-building-with-a-blue-sky-in-the-background-mOBNSq7eCvk",
      es: "una-foto-abstracta-de-un-edificio-azul-con-un-cielo-azul-en-el-fondo-mOBNSq7eCvk",
      ja: "青い空を背景にした青い建物の抽象的な写真-mOBNSq7eCvk",
      fr: "une-photo-abstraite-dun-batiment-bleu-avec-un-ciel-bleu-en-arriere-plan-mOBNSq7eCvk",
      it: "una-foto-astratta-di-un-edificio-blu-con-un-cielo-blu-sullo-sfondo-mOBNSq7eCvk",
      ko: "푸른-하늘을-배경으로-한-파란-건물의-추상-사진-mOBNSq7eCvk",
      de: "ein-abstraktes-foto-eines-blauen-gebaudes-mit-blauem-himmel-im-hintergrund-mOBNSq7eCvk",
      pt: "uma-foto-abstrata-de-um-edificio-azul-com-um-ceu-azul-no-fundo-mOBNSq7eCvk",
      id: "foto-abstrak-bangunan-biru-dengan-latar-belakang-langit-biru-mOBNSq7eCvk",
    },
    created_at: "2023-05-06T17:51:42Z",
    updated_at: "2026-03-01T00:17:12Z",
    promoted_at: "2023-05-10T06:46:56Z",
    width: 3795,
    height: 5823,
    color: "#0ca6c0",
    blur_hash: "L%7z#$fkcEj[a}flj@fQL}fPogf6",
    description: "Photomotage arch photography",
    alt_description:
      "an abstract photo of a blue building with a blue sky in the background",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1683395287409-538f0b93e299?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1683395287409-538f0b93e299?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1683395287409-538f0b93e299?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1683395287409-538f0b93e299?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1683395287409-538f0b93e299?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1683395287409-538f0b93e299",
    },
    links: {
      self: "https://api.unsplash.com/photos/an-abstract-photo-of-a-blue-building-with-a-blue-sky-in-the-background-mOBNSq7eCvk",
      html: "https://unsplash.com/photos/an-abstract-photo-of-a-blue-building-with-a-blue-sky-in-the-background-mOBNSq7eCvk",
      download:
        "https://unsplash.com/photos/mOBNSq7eCvk/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/mOBNSq7eCvk/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 203,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "textures-patterns": {
        status: "approved",
        approved_on: "2024-09-02T14:45:47Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2023-05-10T16:03:09Z",
      },
      "street-photography": {
        status: "rejected",
      },
      "architecture-interior": {
        status: "approved",
        approved_on: "2023-05-17T14:44:58Z",
      },
      blue: {
        status: "approved",
        approved_on: "2023-07-26T19:21:50Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "riTgVdR9Cv4",
      updated_at: "2026-02-24T07:59:59Z",
      username: "nasrphotos",
      name: "Hossein Nasr",
      first_name: "Hossein",
      last_name: "Nasr",
      twitter_username: null,
      portfolio_url: null,
      bio: "22year-old Iranian boy who is fascinated by photography\r\nWelcome to my page dude:)  Explore my photos and enjoy",
      location: "Iran,Tehran",
      links: {
        self: "https://api.unsplash.com/users/nasrphotos",
        html: "https://unsplash.com/@nasrphotos",
        photos: "https://api.unsplash.com/users/nasrphotos/photos",
        likes: "https://api.unsplash.com/users/nasrphotos/likes",
        portfolio: "https://api.unsplash.com/users/nasrphotos/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1679834077450-a14d262d4deaimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1679834077450-a14d262d4deaimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1679834077450-a14d262d4deaimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 13,
      total_likes: 31,
      total_photos: 614,
      total_free_photos: 614,
      total_promoted_photos: 18,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: " EOS 2000D",
      name: "Canon, EOS 2000D",
      exposure_time: "1/1250",
      aperture: "10.0",
      focal_length: "200.0",
      iso: 200,
    },
    location: {
      name: "Tehran, Tehran Province, Iran",
      city: "Tehran",
      country: "Iran",
      position: {
        latitude: 35.721858,
        longitude: 51.334695,
      },
    },
    views: 7270685,
    downloads: 69679,
  },
  {
    id: "akYViZ6nmIA",
    slug: "a-view-of-a-mountain-range-at-sunset-akYViZ6nmIA",
    alternative_slugs: {
      en: "a-view-of-a-mountain-range-at-sunset-akYViZ6nmIA",
      es: "una-vista-de-una-cordillera-al-atardecer-akYViZ6nmIA",
      ja: "夕暮れ時の山脈の眺め-akYViZ6nmIA",
      fr: "une-vue-dune-chaine-de-montagnes-au-coucher-du-soleil-akYViZ6nmIA",
      it: "una-vista-di-una-catena-montuosa-al-tramonto-akYViZ6nmIA",
      ko: "해질녘-산맥의-전망-akYViZ6nmIA",
      de: "blick-auf-eine-bergkette-bei-sonnenuntergang-akYViZ6nmIA",
      pt: "uma-vista-de-uma-cordilheira-ao-por-do-sol-akYViZ6nmIA",
      id: "pemandangan-pegunungan-saat-matahari-terbenam-akYViZ6nmIA",
    },
    created_at: "2023-09-12T08:36:54Z",
    updated_at: "2026-03-01T03:11:43Z",
    promoted_at: "2023-09-15T21:32:01Z",
    width: 2592,
    height: 3888,
    color: "#262659",
    blur_hash: "L_I4I[oKaxj[~Cj@ayj@%La|azfQ",
    description:
      "Within the pre-dawn's embrace, the mountains are bathed in a magical light, unveiling nature's ethereal masterpiece. - Eleonora Patricola",
    alt_description: "a view of a mountain range at sunset",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1694507482314-a429436d4a0a?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1694507482314-a429436d4a0a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1694507482314-a429436d4a0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1694507482314-a429436d4a0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1694507482314-a429436d4a0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1694507482314-a429436d4a0a",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-view-of-a-mountain-range-at-sunset-akYViZ6nmIA",
      html: "https://unsplash.com/photos/a-view-of-a-mountain-range-at-sunset-akYViZ6nmIA",
      download:
        "https://unsplash.com/photos/akYViZ6nmIA/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/akYViZ6nmIA/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 662,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2024-12-12T09:15:18Z",
      },
      nature: {
        status: "approved",
        approved_on: "2023-10-02T12:49:38Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "li-lCwLX5wI",
      updated_at: "2026-02-18T01:29:24Z",
      username: "ele1010",
      name: "Eleonora Patricola",
      first_name: "Eleonora",
      last_name: "Patricola",
      twitter_username: "EEPatricola",
      portfolio_url: "https://eleonorapatricola.com",
      bio: "Front-end Web Developer | UX Designer | Accidental Entrepreneur | Tireless Seeker of Truth in Wilderness | Hiker & Adventurer Climbing Every Mountain ⛰",
      location: "📍 Playing in the mountains",
      links: {
        self: "https://api.unsplash.com/users/ele1010",
        html: "https://unsplash.com/@ele1010",
        photos: "https://api.unsplash.com/users/ele1010/photos",
        likes: "https://api.unsplash.com/users/ele1010/likes",
        portfolio: "https://api.unsplash.com/users/ele1010/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1567799143274-d9fcbb95bfb0image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1567799143274-d9fcbb95bfb0image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1567799143274-d9fcbb95bfb0image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 39,
      total_photos: 118,
      total_free_photos: 118,
      total_promoted_photos: 8,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: null,
        portfolio_url: "https://eleonorapatricola.com",
        twitter_username: "EEPatricola",
        paypal_email: null,
      },
    },
    exif: {
      make: "LEICA",
      model: "V-LUX (Typ 114)",
      name: "LEICA, V-LUX (Typ 114)",
      exposure_time: "1/160",
      aperture: "4.0",
      focal_length: "101.9",
      iso: 125,
    },
    location: {
      name: "Switzerland",
      city: null,
      country: "Switzerland",
      position: {
        latitude: 46.818188,
        longitude: 8.227512,
      },
    },
    views: 6243589,
    downloads: 109040,
  },
  {
    id: "bRtKGtLeNUY",
    slug: "body-of-water-bRtKGtLeNUY",
    alternative_slugs: {
      en: "body-of-water-bRtKGtLeNUY",
      es: "cuerpo-de-agua-bRtKGtLeNUY",
      ja: "水域-bRtKGtLeNUY",
      fr: "plan-deau-bRtKGtLeNUY",
      it: "specchio-dacqua-bRtKGtLeNUY",
      ko: "수역-bRtKGtLeNUY",
      de: "gewasser-bRtKGtLeNUY",
      pt: "corpo-dagua-bRtKGtLeNUY",
      id: "badan-air-bRtKGtLeNUY",
    },
    created_at: "2019-06-04T07:17:28Z",
    updated_at: "2026-03-01T04:48:39Z",
    promoted_at: "2020-02-07T06:06:02Z",
    width: 3648,
    height: 5472,
    color: "#264040",
    blur_hash: "L7C$v8EM0g-TtTNHWBjY=t9vj[%1",
    description: null,
    alt_description: "body of water",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1559632609-e20355f80b92?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1559632609-e20355f80b92?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1559632609-e20355f80b92?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1559632609-e20355f80b92?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1559632609-e20355f80b92?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1559632609-e20355f80b92",
    },
    links: {
      self: "https://api.unsplash.com/photos/body-of-water-bRtKGtLeNUY",
      html: "https://unsplash.com/photos/body-of-water-bRtKGtLeNUY",
      download:
        "https://unsplash.com/photos/bRtKGtLeNUY/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
      download_location:
        "https://api.unsplash.com/photos/bRtKGtLeNUY/download?ixid=M3w4ODUwMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzIzNDMyOTB8",
    },
    likes: 247,
    liked_by_user: false,
    bookmarked: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "-17Zj12ZfQ4",
      updated_at: "2026-01-10T02:05:14Z",
      username: "bradthemann",
      name: "Brad Mann",
      first_name: "Brad",
      last_name: "Mann",
      twitter_username: "bradmannphoto",
      portfolio_url: null,
      bio: "Collection of my favorite photos that I've taken over the years.\r\nFeel free to support me on PayPal if you want to support me!",
      location: "Michigan",
      links: {
        self: "https://api.unsplash.com/users/bradthemann",
        html: "https://unsplash.com/@bradthemann",
        photos: "https://api.unsplash.com/users/bradthemann/photos",
        likes: "https://api.unsplash.com/users/bradthemann/likes",
        portfolio: "https://api.unsplash.com/users/bradthemann/portfolio",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1644264609927-3bd42a4476d0image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1644264609927-3bd42a4476d0image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1644264609927-3bd42a4476d0image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 2,
      total_photos: 62,
      total_free_photos: 62,
      total_promoted_photos: 14,
      total_illustrations: 0,
      total_free_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: "bradmannphoto",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 70D",
      name: "Canon, EOS 70D",
      exposure_time: "1/250",
      aperture: "8.0",
      focal_length: "150.0",
      iso: 200,
    },
    location: {
      name: "Waterford, Michigan",
      city: "Waterford, Michigan",
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 16246426,
    downloads: 8289,
  },
];
